import HeadingCard from '@/components/card/HeadingCard';
import Heading from '@/components/commons/Heading';
import Paragraph from '@/components/commons/Paragraph';

export default function PrivacyPolicyPage() {
  return (
    <>
      <HeadingCard heading={'Privacy Policy'} />
      <img src="3.webp" alt="Your Image" className="w-full h-auto md:h-[50vh] object-cover" />

      <section className="lg:px-44 md:px-30 sm:px-10 px-4 py-16  text-justify">
        <main className="flex flex-col gap-10 text-[14px] sm:text-[15px] text-[#6F6B80]">
          <div className='flex flex-col gap-3'>
            <Heading title="Privacy And Policy" />
            <p>Harshly Education and Skills Technologies Pvt. Ltd. (including its affiliates) is fully committed to upholding its obligations under the applicable privacy laws. This Privacy Policy outlines our unwavering approach to privacy, leaving no room for doubt or ambiguity.</p>
            <p>Throughout this document, the terms “we”, “us”, “our”, “ours” & <span className='text-[#231F40] font-bold'>“HARSHLY GROUP” refer to Harshly Education And Skills Technologies Pvt. Ltd.</span> (including its affiliates). And the terms “you”, “your” “yours” & “you and/or your child “refer to you (as the User of the Platform). Users also include all persons who access, browse, or sign up on the Platform for applying to teach on the Platform (“Applicant(s)”) and those selected to teach on the Platform (“Instructor(s)”).</p>
            <p>This Privacy Policy applies to all your PERSONAL DATA processed by us, whether in physical or electronic mode. This Privacy Policy is meant to help you understand what information we collect, why we collect it, and how you can update, manage, export, and delete your information and shall be read with the Terms and Conditions found on (https://www.easyhaionline.com/terms- policy)www.easyhaionline.com and the COPPA Direct Notice to Parents. Capitalized terms that are not defined in this Privacy Policy have the meaning given to them in the Terms of Conditions.</p>
            <p>By choosing to visit and/or avail any Services provided by us, you agree to this Privacy Policy (as may be amended from time to time). Please read the following information carefully. You must be at least 18 years old to register on our site. If you are under (18) years old, you are not permitted to register unless such registration is completed by a parent or legal guardian. By your continued access or use of the Platform, you signify your agreement to be legally bound by Privacy Policy set forth herein. If you do not agree to the Privacy Policy of this agreement, promptly exit this page and stop accessing the Services. Every effort is made to keep the website up and running smoothly. However, Harshly Education And Skills Technologies Private Limited takes no responsibility for, and will not be liable for, the website being temporarily unavailable due to technical issues beyond our control.</p>
            <p><span className='text-[#231F40] font-bold'>Harshly Education And Skills Technologies Private Limited</span> is located at – C-56/21 ’2nd Floor, Sector -62, Noida , Uttar Pradesh, Pin Code – 201309 eMail :- contact@easyhaionline.com</p>
            <p>We take your trust very seriously at EASYHAIONLINE and we are committed to maintaining high ethical standards when it comes to collecting, using, and protecting your information. As a leading educational technology company based in India, Harshly Education And Skills Technologies Private Limited, operating under the brand name Easyhaionline, offers an array of learning opportunities. Our privacy policy governs the use of the Easyhaionline application ('Application'), www.easyhaionline.com ('Website'), and other products, websites, and services provided by the Company. Before using any of our services, we urge you to read this policy ('Policy') and the Terms of Use ('ToU') provided on the Application and the Website carefully. By using the Application, Website, or Services, or registering with us through any means, you agree to the terms of this Policy and are legally bound by it. If you do not agree to the terms of this Policy, please refrain from using any of our products or services.</p>
          </div>

          <div className='flex flex-col gap-3'>
            <Heading title="User Provided Information (UPI)" />
            <p>Welcome to EASYHAIONLINE! We take pride in our commitment to maintaining ethical standards in collecting, using, and safeguarding any information you provide. As a leading edu-tech company incorporated in India, our privacy policy governs your use of our Application, Website, and all other associated applications, products, websites, and services.</p>
            <p>We believe in providing our users with the best possible experience, and therefore, we ask that you read this privacy policy carefully before using our services. By using our Website, Application, or services, you agree to be legally bound by this Policy and the Terms of Use provided on the Application and the Website. If you do not agree with the terms of this Policy, we kindly ask that you do not use our Website, Application, or avail any of our Services.</p>
            <p>When you register with us, we collect various personal information, including your name, age, email address, location, phone number, password, your ward's educational interests, and transaction-related information. We also collect information you provide us when you contact us for help and when you use the Application/Services/products, such as while asking doubts, participating in discussions, and taking tests. We categorize the information collected from the users as “Personal Information”, “Sensitive Personal Information,” and “Associated Information.”</p>
            <p>Rest assured that we will use the information you provide to contact you from time to time, to provide you with our Services, important information, required notices, and marketing promotions. We will not differentiate between who is using the device to access the Application, Website, or Services/products, as long as the login/access credentials match with yours.</p>
            <p>We fully respect your privacy, and therefore, we always provide you with the option to not provide the Personal Information or Sensitive Personal Information, which we seek from you. Further, you can withdraw your consent given earlier to us to use such Personal Information or Sensitive Personal Information while using the Application/Services/products. Such withdrawal of consent is required to be sent in writing to us at the contact details provided in this Policy.</p>
            <p>We believe that you will have an excellent experience using our Application, Website, and Services/products. However, in the event that you choose to withdraw your consent for us to use your Personal Information or Sensitive Personal Information, we reserve the right not to allow further usage of the Application or provide any Services/products thereunder to you.</p>
            <p className='text-[#231F40] font-bold'>We use this information to:</p>
            <li>provide, test, improve, promote and personalize the Services</li>
            <li>fight spam and other forms of abuse</li>
            <li>generate aggregate, non-identifying information about how people use the Services</li>
            <p>When you create an Easyhaionline account and use a third-party service (such as Twitter, Facebook, Instagram, LinkedIn, Apple, or Google) to authenticate, we confidently collect, store, and periodically update information related to that third-party account. This includes your lists of friends or followers, but please be assured that we will never publish anything through any of your third-party accounts without your express permission. We take your privacy seriously and are committed to keeping your information safe.</p>
          </div>

          <div className='flex flex-col gap-3'>
            <p><span className='text-[#231F40] font-bold'>Information Disclosure:-</span> You can trust that Easyhaionline will never sell or transfer your information to third parties for advertising purposes. Our commitment to your privacy and security is unwavering.</p>
            <p>We may transfer your account information with third parties in some circumstances, including: (1) with your consent; (2) to a service provider or partner who meets our data protection standards; (3) with academic or non-profit researchers, with aggregation, anonymization, or pseudonymization; (4) when we have a good faith belief it is required by law, such as pursuant to a subpoena or other legal process; (5) when we have a good faith belief that doing so will help prevent imminent harm to someone.</p>
            <p>Rest assured that if we ever receive a legal process requesting to share your information, we will notify you beforehand, giving you the chance to challenge it. Although there may be situations where we are prohibited by law or believe that providing notice may endanger others or lead to illegal conduct, we will always object to legal requests for information about our services' users that we consider improper. Your privacy is of utmost importance to us, and we will do everything in our power to protect it.</p>
            <p><span className='text-[#231F40] font-bold'>Public Data:-</span> Rest assured that search engines may index your Easyhaionline user profile page, public interactions (such as claps or highlights), and post pages. This means that people will definitely find these pages when they search for your name on services like Google or Bing. Additionally, other users will likely share links to your content on social media platforms such as Facebook or Twitter.</p>
            <p><span className='text-[#231F40] font-bold'>Data Storage:-</span> At Easyhaionline, we rely on trusted third-party vendors and hosting partners, including Amazon, to provide us with the top-of-the-line hardware, software, networking, storage, and related technology we need to power our services. To ensure the smooth functioning of our services, we maintain two types of logs: server logs and event logs. By using our services, you can be confident that Easyhaionline has the necessary authorization to securely and efficiently transfer, store, and process your information.</p>
            <p>Third-Party Embeds:- Some of the content that you see displayed on Easyhaionline is not hosted by Easyhaionline. These “embeds” are hosted by a third-party and embedded in a Easyhaionline page, so that it appears to be part of that page. For example: YouTube or Vimeo videos, Imgur or Giphy gifs, SoundCloud audio files, Twitter tweets, GitHub code snippets, or Scribd documents that appear within a Easyhaionline post. These files send data to the hosted site just as if you were visiting that site directly (for example, when you load a Easyhaionline post page with a YouTube video embedded in it, that video appears because of a pointer to files hosted by YouTube, and in turn YouTube receives data about your activity, such as your IP address and how much of the video you watch). Easyhaionline doesn’t control what data third parties collect in cases like this, or what they ultimately do with it. So, third-party embeds on Easyhaionline are not covered by this Privacy Policy. They are covered by the privacy policy of the third-party service (so, when you watch a YouTube video embedded in a Easyhaionline post, the use of data about your interactions with the video would be covered by YouTube’s privacy policy.)</p>
            <p>Some embeds may ask you for personal information, such as submitting your email address, through a form linked to from a Easyhaionline post. We do our best to keep bad actors off of Easyhaionline. However, if you choose to submit your information to a third party this way, we don’t know what they may do with it. As explained above, their actions are not covered by this Privacy Policy. So, please be careful when you see embedded forms on Easyhaionline asking for your email address or any other personal information. Make sure you understand who you are submitting your information to and what they say they plan to do with it. We suggest that you do not submit your email address or other personal information to any third-party through an embedded form.</p>
            <p>When posting on Easyhaionline, you may not embed a form that allows submission of personal information by users. You must link offsite to a page that allows such submissions by users, and that page’s appearance must be distinct enough from Easyhaionline to ensure it does not cause confusion among users over to whom they are submitting personal information. Failure to do so may lead Easyhaionline to disable the post or take other action to limit or disable your account.</p>
            <p><span className='text-[#231F40] font-bold'>Tracking & Cookies:-</span> Our Services confidently utilize browser cookies and similar technologies to efficiently identify you when you revisit our website. We use them for various purposes, such as logging you in, remembering your preferences such as default language, evaluating the effectiveness of our email campaigns, enabling our paywall and meter to function seamlessly, and personalizing content and other services tailored to your needs. It is important to note that cookies play a vital role in the basic functioning of Easyhaionline's metered paywall, and without them, it would not operate as intended.</p>
            <p>Easyhaionline saves data about the URLs you Save to Easyhaionline (an optional feature that you may choose to use or decline to use), but we do not otherwise track your visits or activities off Easyhaionline Services. We track your interactions within the Easyhaionline Services (which encompasses Easyhaionline.com, custom domains hosted by Easyhaionline, and your interactions with our mobile application).</p>
            <p>Some third-party services that we use to provide the Service, such as Google Analytics, may place their own cookies in your browser. This Privacy Policy covers use of cookies by Easyhaionline only and not the use of cookies by third parties.</p>
            <p>Modifying or Deleting Your Personal Information:- If you have a Easyhaionline account, you can access, modify or export your personal information, or delete your account here.</p>
            <p>To protect information from accidental or malicious destruction, we may maintain residual copies for a brief time period (generally several weeks). But, if you delete your account, your information and content will be unrecoverable after that time. Easyhaionline may preserve and maintain copies of your information beyond this time period when required to do so by law.</p>
            <p><span className='text-[#231F40] font-bold'>Data Security:-</span> We use encryption (HTTPS/TLS) to protect data transmitted to and from our site. However, no data transmission over the Internet is 100% secure, so we can’t guarantee security. You use the Service at your own risk, and you’re responsible for taking reasonable measures to secure your account.</p>
            <p><span className='text-[#231F40] font-bold'>Business Transfers:-</span> If we’re involved in a merger, acquisition, bankruptcy, reorganization or sale of assets such that your information would be transferred or become subject to a different privacy policy, we’ll notify you in advance so you can opt out of any such new policy by deleting your account before transfer.</p>
            <p><span className='text-[#231F40] font-bold'>Email from Easyhaionline:-</span> Sometimes we’ll send you emails about your account, service changes or new policies. You can’t opt out of this type of “transactional” email (unless you delete your account). But, you can opt out of non-administrative emails such as digests, newsletters, and activity notifications through your account’s Settings page. When you interact with an email sent from Easyhaionline (such as opening an email or clicking on a particular link in an email), we may receive information about that interaction. We won’t email you to ask for your password or other account information. If you receive such an email, please forward it to us at support@easyhaionline.com so we can investigate</p>
            <p><span className='text-[#231F40] font-bold'>Changes to this Policy:-</span> Easyhaionline may periodically update this Policy. We’ll notify you about significant changes to it. The most current version of the policy will always be here and we will archive former versions of the policy here.</p>
            <p>Questions:- We welcome feedback about this policy atcontact@easyhaionline.com</p>
            <p>Data Protection Statement:- Easyhaionline collects and stores personal information about its users to customize their reading experience and enable personalized distribution of content. It shares minimal data with its service providers.</p>
          </div>

          <div className='flex flex-col gap-3'>
            <Heading title="Purposes of Processing" />
            <div>
              <li>Provide, test, promote, and improve the Services</li>
              <li>Gather usage statistics of services</li>
              <li>Provide customized reading experience</li>
              <li>Publish and distribute user-generated content</li>
              <li>Provide access to paid content</li>
              <li>Pay authors in Partnership Program for certain content</li>
              <li>Fight spam, fraud, and other abuse of services</li>
            </div>
          </div>

          <div className='flex flex-col gap-3'>
            <Heading title="Legal Bases" />
            <p>In order to provide the Services, EasyhaiOnline collects and stores personal data about its users to fulfil its contractual obligations to users as described in our Terms of Service and to Members as described in our Membership Terms of Service.</p>
            <p>EasyhaiOnline also pursues its legitimate interests by collecting minimal data of logged out users to provide the Services, as outlined above, as well as to ensure that new users trying out the free member preview do not exceed their maximum limit of free articles per month before a paid subscription is required to read further. These legitimate interests are not outweighed by (nor do they violate) our users’ privacy interests because we collect minimal user data for these purposes and we are fully transparent about these activities.</p>
            <p>Where EasyhaiOnline collects and stores personal data about non-users mentioned in user- generated content, it does so under performance of contract obligations to users who use the 5 | P a g e Services to publish content on web sites hosted by EasyhaiOnline. In such cases, users authoring such user-generated content containing personal data of third parties are responsible for that content. EasyhaiOnline will consider related complaints in compliance with the General Data Protection Regulation’s rights of the data subject, as well as rights of expression and access to information.</p>
            <p>Categories of Personal Data Collected</p>

            <div><span className='text-[#231F40] font-bold'> Logged out users:</span>
              <li>Reading history</li>
              <li>IP address</li>
              <li>Browser information</li>
              <li>DNT status</li></div>

            <div>
              <span className='text-[#231F40] font-bold'>Logged in users:</span>
              <li>Reading history</li>
              <li>Username</li>
              <li>Display name</li>
              <li>Bio</li>
              <li>Avatar image</li>
              <li>Email address (non-public)</li>
              <li>Session activity (security)</li>
              <li>Linked social media accounts (optional)</li>
              <li>IP address</li>
              <li>Browser information</li>
              <li>Reading history (on Medium Services only)</li>
              <li>Meta-data about URLs saved by using the optional feature Save to Medium</li>
              <li>Network interactions (recommends, follows, etc.)</li>
              <li>Posts, responses, or series published by user</li>
            </div>

            <div>
              <span className='text-[#231F40] font-bold'>Members:</span>
              <li>Billing information and history</li>
            </div>

            <div>
              <span className='text-[#231F40] font-bold'>Partner authors:</span>
              <li>Bank account for payments</li>
              <li>Business information, if applicable</li>
            </div>
          </div>

          <div>
            <Heading title="Contact Information" />
            <p className="mt-3">If you have any questions about this Privacy Policy, you can contact us at contact@easyhaionline.com,. We have also appointed a representative in the Easyhaionline to receive inquiries about our processing of personal data. To make such an inquiry, please contact Easyhaionline using this contact form: https://www.easyhaionline.com/privacy- services.</p>
          </div>

          <div>
            <Heading title="Or you can contact them at:" />
            <p className="mt-3">M/s Harshly Education and Skills Technologies Pvt. Ltd.C-56/21, 2nd Floor, Sector-62, Noida, Uttar Pradesh, -201309 Email. contact@easyhaionline.com Phone +91 120 4360796</p>
          </div>

          <div className='flex flex-col gap-3'>
            <p><span className='text-[#231F40] font-bold'>Terms and Conditions Policy:-</span> We highly value your trust and are committed to maintaining ethical standards when it comes to handling any information you provide us. As a leading education tech company, Harshly Education And Skills Technologies Private Limited, operating under the brand name Easyhaionline, we strive to provide you with the best possible learning experiences.</p>
            <p>Our privacy policy governs your use of the Easyhaionline application, website, and other associated products and services managed by our company. We encourage you to carefully read this policy along with our terms of use before using any of our services. By using our website, application, or services, you are agreeing to the terms of our policy and are legally bound by them.</p>
            <p>Should you have any concerns or questions about our privacy policy or how we handle your information, please do not hesitate to contact us. We are committed to providing you with the best possible service and will do our utmost to address any concerns you may have.</p>
          </div>

          <div>
            <Heading title="User Provided Information (UPI)" />
            <p className="mt-3">
              The Application Website, Services, products obtains the information you provide when you download and register for the Application or Services or products. When you register with us, you generally provide (a) your name, age, email address, location, phone number, password and your ward's educational interests; (b) transaction-related information, such as when you make purchases, respond to any offers, or download or use applications from us; (c) information you provide us when you contact us for help. (d) Information you enter into our system when using the Application/Services/products, such as while asking doubts, participating in discussions and taking tests. The said information collected from the users could be categorized as “Personal Information”, “Sensitive Personal Information” and “Associated Information”. Personal Information, Sensitive Personal Information and Associated Information (each as individually defined under this Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011 (the “Data Protection Rules”) shall collectively be referred to as 'Information' in this Policy. We may use the Information to contact you from time to time, to provide you with the Services, important information, required notices and marketing promotions. We will ask you when we need more information that personally identifies you (personal information) or allows us to contact you. We will not differentiate between who is using the device to access the Application, Website or Services or products, so long as the log in/access credentials match with yours. In order to make the best use of the Application/Website/Services/products and enable your Information to be captured accurately on the Application/Website/Services/products, it is essential that you have logged in using your own credentials. We will, at all times, provide the option to you to not provide the Personal Information or Sensitive Personal Information, which we seek from you. Further, you shall, at any time while using the Application/Services/products, also have an option to withdraw your consent given earlier to us to use such Personal Information or Sensitive Personal Information. Such withdrawal of the consent is required to be sent in writing to us at the contact details provided in this Policy below. In such event, however, the Company fully reserves the right not to allow further usage of the Application or provide any Services/products thereunder to you.
            </p>
          </div>

          <div>
            <Heading title="Automatically Collected Information" />
            <p className="mt-3">We strive to make the Application, products, and services more efficient and user-friendly. To achieve this, we automatically collect specific information, such as the type of mobile device you use, your mobile device's unique ID, your mobile device's IP address, your mobile operating system, and the type of mobile internet browsers you use. Additionally, we may collect other relevant information based on the permissions you provide. Please rest assured that these companies will not retain, share, store, or use personally identifiable information for any other purpose.</p>
          </div>

          <div className='flex flex-col gap-3'>
            <Heading title="Use of your Personal Information" />
            <p>We use the collected Information to analyse trends, to conduct research, to administer the Application/Services and products, to learn about each user's learning patterns and movements around the Application/Services and products and to gather demographic information and usage behaviour about our user base as a whole. Aggregated and individual, anonymized and non-anonymized data may periodically be transmitted to external service providers to help us improve the Application, products and our Services. We will share your information with third parties only in the ways that are described below in this Policy. We may use the individual data and behaviour patterns combined with personal information to provide you with personalized content, and better your learning objectives. Third parties provide certain services which we may use to analyse the data and information to personalize, drive insights and help us better your experience or reach out to you with more value added applications, products, information and services. However, these third party companies do not have any independent right to share this information. We do not sell, trade or share your Information to any third party (except subsidiaries/affiliates of the Company for related offerings) unless, we have been expressly authorized by you either in writing or electronically to do so. We may at times provide aggregate statistics about our customers, traffic patterns, and related site information to reputable third parties; however this information when disclosed will be in an aggregate form and does not contain any of your Personally Identifiable Information. EASYHAIONLINE will occasionally send email notices, and messages or contact you to communicate about our Services, products, and benefits, as they are considered an essential part of the Services/products you have chosen. We may disclose Information:</p>

            <li>As required by law, such as to comply with a subpoena or similar legal process.</li>
            <li>To enforce applicable Terms of Use ('ToU'), including investigation of potential violations thereof when we believe in good faith that disclosure is necessary to protect our rights, protect your safety or the safety of others, investigate fraud, address security or technical issues or respond to a government request with our trusted services providers who work on our behalf, do not have an independent use of the information we disclose to them, and have agreed to adhere to the rules set forth in this Policy to protect against imminent harm to the rights, property or safety of the Application/Website/ Harshly Education And Skills Technologies Pvt. Ltd. Or its users or the public as required or permitted by law with third-party service providers in order to personalize the Application/Website/Services/products for a better user experience and to perform behavioral analysis.</li>
            <li>Any portion of the Information containing personal data relating to minors provided by you shall be deemed to be given with the consent of the minor's legal guardian. Such consent is deemed to be provided by your registration with us.</li>
          </div>

          <div className='flex flex-col gap-3'>
            <p><span className='text-[#231F40] font-bold'>Access to your Personal Information</span> We will provide you with the means to ensure that your Personal Information is correct and current. If you have filled out a user profile, we will provide an obvious way for you to access and change your profile from our Application/Services/Website/products. We adopt reasonable security measures to protect your password from being exposed or disclosed to anyone.</p>
            <p><span className='text-[#231F40] font-bold'>Cookies</span> We send cookies (small files containing a string of characters) to your computer, thereby uniquely identifying your browser. Cookies are used to track your preferences, help you log in faster, and be aggregated to determine user trends. This data is used to improve our offerings, such as providing more content in areas of greater interest to a majority of users. Most browsers are initially set up to accept cookies, but you can reset your browser to refuse all cookies or to indicate when a cookie is being sent. Some of our features and services may not function properly if your cookies are disabled.</p>
            <p><span className='text-[#231F40] font-bold'>Links</span> We may present links in a format that enables us to keep track of whether these links have been followed. We use this information to improve our customized content. Clicking on links may take you to sites outside our domain. We are not responsible for the privacy practices of other websites. We encourage our users to be aware when they leave our site to read the privacy statements of each and every website that collects personally identifiable information. This Privacy Policy applies solely to information collected by our website.</p>
            <p><span className='text-[#231F40] font-bold'>Alerts</span> We may alert you by email or phone (through SMS/call) to inform you about new service offerings of the company and its subsidiaries/affiliates or other information which we feel might be useful for you, through the Company or its subsidiaries/affiliates.</p>
            <p><span className='text-[#231F40] font-bold'>Public Forums</span> When you use certain features on our website like the discussion forums and you post or share your personal information such as comments, messages, files, photos, will be available to all users, and will be in the public domain. All such sharing of information is done at your own risk. Please keep in mind that if you disclose personal information in your profile or when posting on our forums this information may become publicly available.</p>
            <p><span className='text-[#231F40] font-bold'>Security</span> We are concerned about safeguarding the confidentiality of your Information. We provide physical, electronic, and procedural safeguards to protect Information we process and maintain. For example, we limit access to this Information to authorized employees only who need to know that information in order to operate, develop or improve our Application/Services/products/Website. Please be aware that, although we endeavour to provide reasonable security for information we process and maintain, no security system can prevent all potential security breaches.</p>
            <p><span className='text-[#231F40] font-bold'>How Long Do We Retain User Data?</span> Currently, we plan to retain user data while an account is active and for at least three years afterward. We may alter this practice according to legal and business requirements. For example, we may lengthen the retention period for some data if needed to comply with law or voluntary codes of conduct. Unless otherwise prohibited, we may shorten the retention period for some types of data if needed to free up storage space.</p>
            <p><span className='text-[#231F40] font-bold'>Log information</span> When you access our Website, our servers automatically record information that your browser sends whenever you visit a website. These server logs may include information such as your web request, internet protocol address, browser type, browser language, the date and time of your request and one or more cookies that may uniquely identify your browser.</p>
            <p><span className='text-[#231F40] font-bold'>User communications</span> When you send an email or other communication to us, we may retain those communications in order to process your inquiries, respond to your requests and improve our Services.</p>
            <p><span className='text-[#231F40] font-bold'>Changes to this Statement</span> As the company develops, our Privacy Policy will need to evolve as well as cover new situations. You are advised to review this policy regularly for any changes, as continued use is considered an approval of all changes.</p>
            <p><span className='text-[#231F40] font-bold'>You’re Consent</span> We believe that, every user of our Application/Services/products/Website must be in a position to provide an informed consent prior to providing any Information required for the use of the Application/Services/products/Website. By registering with us, you are expressly consenting to our collection, processing, storing, disclosing and handling of your information as set forth in this Policy now and as amended by us. Processing, your information in any way, including, but not limited to, collecting, storing, deleting, using, combining, sharing, transferring and disclosing information, all of which activities will take place in India. If you reside outside India your information will be transferred, processed and stored in accordance with the applicable data protection laws of India.</p>
            <p><span className='text-[#231F40] font-bold'>Grievance Contact Information</span> Our Grievance Officer shall undertake all reasonable efforts to address your grievances at the earliest possible opportunity. You may contact us at: Grievance Officer: Mr. Anil Kumar, Address: C-56/21, 2nd Floor Sector-62 Noida-201309, Uttar Pradesh, India, Reach out to us on grievance@easyhaionline.com, in case of any queries.</p>
          </div>
        </main>
      </section>
    </>
  );
}

const para = {
  para1:
    ' Pellentesque ut varius leo. Quisque dignissim, orci in iaculis facilisis, tortor ipsum laoreet ligula, sed aliquam dolor nisl non ligula. Aenean dignissim ligula aliquam sem non felis placerat auctor, eu laoreet nibh pharetra. Phasellus nec lectus purus. Sed vitae lectus libero. Pellentesque vel lorem ligula. Maecenas eu orci non felis placerat malesuada non felis placerat . Aliquam erat volutpat. Fusce et nisl non justo viverra tincidunt. Ut cursus enim vitae facilisis ornare. Nullam auctor, mi ac tempor mollis, justo sem pretium magna, at non felis placerat elementum purus nulla facilisis eros. Sed posuere felis ut ipsum faucibus, a sagittis quam sodales. Donec in dui diamPellentesque ut varius leo. Quisque dignissim, orci in iaculis facilisis, tortor ipsum laoreet ligula, sed aliquam dolor nisl non ligula. Aenean dignissim ligula aliquam sem vel lorem ligula. Maecenas eu orci non felis placerat malesuada Donec in dui diam... auctor, eu laoreet nibh pharetra. Phasellus nec lectus purus. Sed vitae lectus libero. Pellentesque vel lorem ligula. Maecenas eu orci non felis placerat malesuada. Donec in dui diam.. Aliquam erat volutpat. Fusce et nisl non justo viverra tincidunt. Ut cursus enim vitae facilisis ornare. Nullam auctor, mi ac tempor mollis, justo sem pretium magna, at Donec in dui diam.. elementum purus nulla facilisis eros. Sed posuere felis ut ipsum faucibus, a sagittis quam sodales. Donec in dui diam..',
  para2:
    ' Lorem ipsum dolor sit amet consectetur. Tristique sed morbi egestas ultrices. Ut amet nisl nulla id justo amet tortor integer donec. Amet nunc urna sagittis felis facilisi cursus id aenean. Cursus eget turpis tristique hac. Vulputate lacinia aenean vitae scelerisque eget fermentum pellentesque leo in. Et tincidunt lorem et viverra neque blandit a volutpat diam. Mi volutpat non mi mi pretium nibh gravida mauris. Enim duis scelerisque tincidunt a. Arcu velit ut neque pellentesque et semper amet. Vehicula purus laoreet feugiat commodo posuere ipsum neque viverra integer. Dolor pharetra bibendum aenean gravida. Varius venenatis malesuada est nec. Amet ullamcorper pretium nulla netus congue enim vitae.',
  para3:
    " 2 | P a g e Terms and Conditions Privacy Policy We value your trust. In order to honour that trust, EASYHAIONLINE adheres to ethical standards in gathering, using, and safeguarding any information you provide. Harshly Education And Skills Technologies Private Limited (operating under the brand name Easyhaionline, is a leading edu- tech, company, incorporated in India, for imparting learning. This privacy policy governs your use of the application 'Easyhaionline ('Application'), www.easyhaionline.com ('Website') and the other associated applications, products, websites and services managed by the Company. Please read this privacy policy ('Policy') carefully before using the Application, Website, our services and products, along with t he Terms of Use ('ToU') provided on the Application and the Website. Your use of the Website, Application, or services in connection with the Application, Website or products ('Services'),",
  para4:
    '  Duis vitae vehicula risus. Morbi justo mauris, accumsan sed purus ac, varius viverra orci. Donec ut nunc sodales, posuere enim at, egestas erat.',
};

